import 'package:flutter/material.dart';
import 'styles/styles.dart';
import 'mocks/mock_location.dart';
import 'models/location.dart';

class LocationDetail extends StatelessWidget {
  final int locationID;

  LocationDetail(
      this.locationID); // Constructor now accepts the 'index' of the LocationList selected from the ListView instead of a new class 'location' that is a copy of the MockLocation

  @override
  Widget build(BuildContext context) {
    var location = MockLocation.fetch(this.locationID);
    return Scaffold(
      appBar: AppBar(title: Text(location.name, style: Styles.navBarTitle)),
      body: SingleChildScrollView(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: _renderBody(context, location),
        // Column's children is a list of widgets generated by _renderBody (requires context) and a location object (named location) consisting of one location created by calling static function Fetch to populate the location class variable with one entry base on the index passed by the ListView above
      )),
    );
  }

  List<Widget> _renderBody(BuildContext context, Location location) {
    var result = <Widget>[];
    result.add(_bannerImage(location.url, 170.0));
    result.addAll(_renderFacts(context, location));
    return result;
  }

  List<Widget> _renderFacts(BuildContext context, Location location) {
    var result = <Widget>[];
    for (int i = 0; i < location.facts.length; i++) {
      result.add(_factTitle(location.facts[i].title));
      result.add(_factText(location.facts[i].text));
    }
    return result;
  }

  Widget _bannerImage(String url, double height) {
    return Container(
      constraints: BoxConstraints.tightFor(height: height),
      child: Image.network(url, fit: BoxFit.fitWidth),
    );
  }

  Widget _factTitle(String text) {
    return Container(
        padding: EdgeInsets.fromLTRB(25.0, 25.0, 25.0, 10.0),
        child:
            Text(text, textAlign: TextAlign.left, style: Styles.textHeader1));
  }

  Widget _factText(String text) {
    return Container(
        padding: EdgeInsets.fromLTRB(25.0, 15.0, 15.0, 15.0),
        child:
            Text(text, textAlign: TextAlign.left, style: Styles.textDefault));
  }
}
